name: ctnns
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - blas=1.0
  - ca-certificates=2019.11.27
  - catalogue=1.0.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cpuonly=1.0
  - cryptography=2.8
  - cymem=2.0.3
  - dbus=1.13.12
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.4.0
  - intel-openmp=2019.4
  - jpeg=9b
  - jsonschema=3.2.0
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.1.0
  - murmurhash=1.0.0
  - ncurses=6.1
  - ninja=1.9.0
  - nltk=3.4.5
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.3
  - patsy=0.5.1
  - pcre=8.43
  - pillow=7.0.0
  - pip=19.3.1
  - plac=0.9.6
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - pytz=2019.3
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - seaborn=0.9.0
  - setuptools=44.0.0
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - srsly=1.0.0
  - statsmodels=0.10.1
  - tk=8.6.8
  - torchvision=0.4.2
  - tornado=6.0.3
  - tqdm=4.41.1
  - urllib3=1.25.7
  - wasabi=0.6.0
  - wheel=0.33.6
  - xz=5.2.4
  - zipp=1.0.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - alabaster==0.7.12
    - allennlp==0.9.0
    - babel==2.8.0
    - bert-embedding==1.0.1
    - blis==0.2.4
    - boto3==1.11.2
    - botocore==1.14.2
    - click==7.0
    - conllu==1.3.1
    - cycler==0.10.0
    - docutils==0.16
    - editdistance==0.5.3
    - flaky==3.6.1
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.6
    - gevent==1.4.0
    - gluonnlp==0.6.0
    - greenlet==0.4.15
    - h5py==2.10.0
    - imagesize==1.2.0
    - itsdangerous==1.1.0
    - jinja2==2.10.3
    - jmespath==0.9.4
    - joblib==0.14.1
    - jsonnet==0.14.0
    - jsonpickle==1.2
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mxnet==1.4.0
    - numpy==1.14.6
    - numpydoc==0.9.2
    - overrides==2.8.0
    - packaging==20.0
    - parsimonious==0.8.1
    - pluggy==0.13.1
    - preshed==2.0.1
    - protobuf==3.11.2
    - py==1.8.1
    - pygments==2.5.2
    - pytest==5.3.2
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - regex==2020.1.8
    - responses==0.10.9
    - s3transfer==0.3.0
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - sentencepiece==0.1.85
    - snowballstemmer==2.0.0
    - spacy==2.1.9
    - sphinx==2.3.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - sqlparse==0.3.0
    - tensorboardx==2.0
    - thinc==7.0.8
    - typing==3.6.6
    - unidecode==1.1.1
    - wcwidth==0.1.8
    - werkzeug==0.16.0
    - word2number==1.1
